apiVersion: v1
kind: Secret
metadata:
  name: prometheus-secret
type: Opaque
stringData:
  web.yml: |
    basic_auth_users:
      admin: "$2a$12$fApg6iekysJsivXJV5uQNOpNZ6nroqLPNTp0OoUQNbfhKfsGZIC0W"
