apiVersion: v1
kind: Service
metadata:
  name: {{ include "miniapp-chart.fullname" . }}
  labels:
    {{- include "miniapp-chart.labels" . | nindent 4 }}

spec:
  selector:
    {{- include "miniapp-chart.selectorLabels" . | nindent 4 }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
